### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-mention#12]
![image](https://user-images.githubusercontent.com/156149/55092617-23b5dd00-50b3-11e9-845d-58c9a7e89731.png)

**Comment by jodator** [comment]
Waiting for: https://github.com/ckeditor/ckeditor5-engine/pull/1705 - after I should apply @scofalik suggestions about that behavior:

> However, this does not fix not-bolding on undo. In fact, everything works correctly. The bold is applied, but since also there is a letter inserted (or removed) during the undo, the bold is immediately taken off.
>
> So the post-fixer like this for mentions is not correct.

**Comment by Reinmar** [comment]
To make it clear – SC's PR does not fix those tests. I'm going to merge it, though, because it looks good.
