### ISSUE TITLE
Can marker be two+ characters?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-mention#23]
E.g. if I want to autocomplete placeholders, I'd like to use `[[`.

**Comment by Reinmar** [comment]
A manual test would be good.

**Comment by jodator** [comment]
I'm not 100% right now - it might be simplified to one character in some places.

**Comment by Reinmar** [comment]
We came to a conclusion that in such case it won't be the "mentions" feature anymore, but a more general "autocomplete" so I'm closing this issue.

**Comment by mariusrak** [comment]
What is wrong with "more general autocomplete" ? I think It would be nice to allow such functionality even if name of plugin doesn't promise it. Besides it doesn't have to be used as autocompletition. I might want to have mentions in format [[name]] and it wouldn't be possible with such constriction. It also seems like artificially made constriction. 

Is there any technological reason, why the plugin should not allow markers longer than 1 char? If not I think, that this proposal should be reconsidered and constriction eventually removed.

**Comment by jodator** [comment]
@mariusrak It adds some complexity to the API and we would probably not cover all cases in the `Mention` plugin alone. Hence more general `AutoComplete` plugin/guide will be provided (no dates as for now) so one could create a similar feature by using CKEditor API and have it customized beyond what `Mention` plugin alone provides.

**Comment by mariusrak** [comment]
Well, now I noticed in the code one condition which prohibits it. If the condition would be removed and I'd use two cahrs for suggestion, would it somehow influence working of the plugin? Becuase if not, then it seems like this way is more complex since there one more constriction.
