### ISSUE TITLE
Up/down arrows are locked

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-mention#28]
I recorded pressing:

* right (moves caret),
* left (moves caret),
* top/bottom (irreversibly changes item selection, locks the caret).

![Apr-03-2019 11-25-21](https://user-images.githubusercontent.com/156149/55468402-9703a580-5603-11e9-9294-604ce35db2fc.gif)

I don't think that up/down should be locked. But if you think it should, then at least the item selection should not be changed (if there's just one item).

**Comment by jodator** [comment]
I think that's a minor bug in selection cycling - the item is unselected but should not. You still can move caret and execute selected (even if not visually) item. Should be easy fix.

**Comment by Reinmar** [comment]
I just realised that we must be locking the up/down arrows because they are normally used to navigate in this panel :D That didn't occur to me initially.

So, yeah, let's fix selection cycling.
