### ISSUE TITLE
Limit number of auto-complete options in mentions panel

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-mention#3]
There should be some CSS rules to limit the size of auto-complete suggestions in mentions panel view:

![Selection_250](https://user-images.githubusercontent.com/247363/54989620-33e99180-4fb9-11e9-808a-8584f829fcaa.png)

**Comment by dkonopka** [comment]
☝️ With maximum height of panel, we should add here support [overscroll-behaviour: contain](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) to get rid of "double scroll trap".

**Comment by Reinmar** [comment]
I think we should also recommend to return a `.slice( 0, 10 )` in the feed callback. There's no point to render 10000 results for a generic query.
