### ISSUE TITLE
The mention list should highlight the last item when the list is displayed above the text.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-mention#36]
This scenario is OK (highlighted suggestion is next to cursor):
![Selection_283](https://user-images.githubusercontent.com/247363/55540304-02607c80-56c3-11e9-8968-2decd27cc10c.png)

This scenario is NOT OK (highlighted suggestion is far away from caret):
![Selection_282](https://user-images.githubusercontent.com/247363/55540284-f5dc2400-56c2-11e9-84c0-2f1f822928d0.png)

**Comment by mlewand** [comment]
TBH I don't think this is a good approach in terms of discoverability. As a result user is unable to predict which item will be selected.

Two more reasons:
* The first (top) result should always be the **best** match.
* Consider that there's space only for 3 matches below the caret (which is preferred position) and you have 5 matches from the db. Assuming your expected the dropdown would appear on top and the last (bottom) item would be selected, now imagine that you type more chars to narrow down the selection and you have 3 responses. Dropdown goes to bottom and should the selection go to the first (top) item?

I'll close the issue but feel free to provide more arguments if you disagree with this.

**Comment by oleq** [comment]
> * The first (top) result should always be the **best** match.

That's the top argument against it. Also in the context of a11y.
