### ISSUE TITLE
Should mentions be upcasted on paste?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-mention#50]
For instance, should pasting `@Ted is a nice fellow` automatically upcast `@Ted` in the feature guide?

**Comment by oleq** [comment]
cc @Reinmar @jodator

**Comment by Reinmar** [comment]
I don't think so. Unless mentions are in the pasted data (so it's not a plain-text), but then we also need to match those mentions with the feed, because the actual data may come from a different editor which had a different mentions config.

**Comment by jodator** [comment]
the text alone wasn't considered a mention - ie when you type `@ted` and discard the mention button then it stays as plain text.

**Comment by Reinmar** [comment]
@jodator, I think that @oleq asked what should happen if you paste "@Ted is a nice fellow", which is a different case than pasting "@Ted"

**Comment by jodator** [comment]
> @jodator, I think that @oleq asked what should happen if you paste "@ted is a nice fellow", which is a different case than pasting "@ted"

Well that's just more letters :) for me those are the same cases: plain text `@ted` with optional text around, inside bigger chunks of texts or just `@ted` without markup it should be treated as plain text as you wrote.

**Comment by mlewand** [comment]
+1 to the idea of treating plain text, well, as a plain text.
