### ISSUE TITLE
Autocompletion panel should not appear on delete

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-mention#6]
![Mar-27-2019 09-32-21](https://user-images.githubusercontent.com/156149/55061217-7a9bc200-5073-11e9-8e80-e50c3fbc114b.gif)

I think it should only be triggered by typing. It can still *be shown* after someone pressed e.g. "@", "xyz", and then pressed backspace. But it should not *appear* on backspace.

**Comment by Reinmar** [comment]
cc @dkonopka @oleq wdyt?

**Comment by dkonopka** [comment]
I wasn't so sure about it in the beginning, but after some time "playing" with mentions, I agree with you, this looks just weird.

Still, as you said, it should be possible to fix my mention while typing:

`@f` -> `@fo[] (pressing backspace)` -> `@f` (the panel should be visible).

**Comment by oleq** [comment]
So the rule of thumb would be that if backspacing begun after the mention, the panel should not appear. But if already in a mention, then backspacing should display the panel. Am I right?

**Comment by jodator** [comment]
@mlewand & @Reinmar so we go with:
> So the rule of thumb would be that if backspacing begun after the mention, the panel should not appear. But if already in a mention, then backspacing should display the panel. Am I right?

?

If so just change label to confirmed and I be good to go :)

**Comment by Reinmar** [comment]
I played with Slack and GH a bit. Both show the panel on backspace... I never noticed it so perhaps it's not that annoying. @oleq also didn't see it as a big problem, so maybe we can ignore this issue for now.

However, there's actually a different problem on:

![Mar-27-2019 09-32-21](https://user-images.githubusercontent.com/156149/55061217-7a9bc200-5073-11e9-8e80-e50c3fbc114b.gif)

If the panel appears on backspace, we should be consistent here. So the issue is – why doesn't it appear for `@Te[]`?

**Comment by jodator** [comment]
> If the panel appears on backspace, we should be consistent here. So the issue is – why doesn't it appear for `@Te[]`

:+1: for consistency - maybe it's some events ordering issue - I can check if this could be easily fixed.

**Comment by jodator** [comment]
@Reinmar: I couldn't reproduce this issue on latest master. Also from your screen cast it looks like some older version:

![Peek 2019-05-29 13-27](https://user-images.githubusercontent.com/247363/58553618-a2470c00-8215-11e9-90fc-ce4059ecdc64.gif)

So if the issue form @Reinmar's [comment](https://github.com/ckeditor/ckeditor5-mention/issues/6#issuecomment-494772615) doesen't occur we can close this one? /cc @mlewand

**Comment by Reinmar** [comment]
Yup, I can confirm it works fine now. So I'm closing this.
