### ISSUE TITLE
Mentions does not works well with the rotator

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-mention#74]
After https://github.com/ckeditor/ckeditor5-mention/issues/67 was closed I tested how mentions work with the rotator and unfortunately it does not work well:

![mentions-rotator](https://user-images.githubusercontent.com/1166967/58417493-3b92e880-8085-11e9-86df-15465347c462.gif)

Issues:
1. Error in the console:
```
rect.js:72 Uncaught (in promise) TypeError: Cannot read property '_source' of null
    at new Rect (rect.js:72)
    at MentionsView._isItemVisibleInScrolledArea (mentionsview.js:127)
    at MentionsView.select (mentionsview.js:109)
    at MentionsView.selectFirst (mentionsview.js:48)
    at MentionUI._showUI (mentionui.js:397)
    at eval (mentionui.js:351)
```
2. Mentions appears behind comment.
3. There is rotator above suggested options.

I believe when mentions balloon appears it should be one and only panel to be displayed.

After the talk with @jodator, we agreed it should be solved as a part of the Contextual Balloon. There should be a flag to prevent other stacks to be displayed.

I think we should have something like this:

`contextualBalloon.add( { view, preventOtherStacks = true } )`.

It should not remove any stacks from the contextualBalloon data, but prevent them from being displayed as long as the view with `preventOtherStacks` is added.

**Comment by pjasiun** [comment]
Alternatively, we should have a separate method:
```
contextualBalloon.forceSingleStack( 'main' );
contextualBalloon.forceSingleStack( false );
```
/cc @Reinmar WDYT?

**Comment by jodator** [comment]
> Alternatively, we should have a separate method:

Depending on use cases... I wonder if we gonna need switching type of panel added to the ContextualBalloon. Right now we need a way do define that a view should be displayed without others - and we know about it at them moment of adding a view. And I don't see in near feature hybrid views - ie such when in some condition it should be single but in other it can be added to the rotator.

So going with this I'd start with `contextualBalloon.add( { view, preventOtherStacks = true } )` and add a possibility to on/off the rotator later on when needed.

**Comment by pjasiun** [comment]
```js
contextualBalloon.add( { view, singleViewMode = true } )
```
