### ISSUE TITLE
Postfixer should remove the whole mention when it's build from two+ text nodes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-mention#8]
![Mar-27-2019 09-47-15](https://user-images.githubusercontent.com/156149/55062444-4b3a8480-5076-11e9-9210-3a2874e0c1d4.gif)

**Comment by jodator** [comment]
I was thinking about such cases and forgot to create a follow-up for this. I wonder how mention should behave when someone would try to style the mention?

Right now it allows to style part of a mention but shouldn't we disallow this? Enforce whole text node to be selected when applying attribute?

**Comment by Reinmar** [comment]
It's tricky... The most problematic part is that in the output you'll get a split span, so processing such content would be hard.

We've got two options:

* prevent applying styling to part of a mention by either extending the style to the whole mention or not applying it,
* remove the mention when part of it was styled.

The latter seems easier.

Do we have some examples how others approached this?

**Comment by jodator** [comment]
Quick check:

Slack breaks mention into "partial match" mention:

![Selection_257](https://user-images.githubusercontent.com/247363/55162960-2d018100-5169-11e9-808f-4a9c0137b3cc.png)

Github extends bold:
`foo @Rein**mar  bar**`: foo @Rein**mar  bar**

Gitlab - broken mention:
![Selection_260](https://user-images.githubusercontent.com/247363/55163343-efe9be80-5169-11e9-80ed-f37c334677b8.png)


Twitter, Facebook - no styling no problem

**Comment by jodator** [comment]
Balloon positioning:

1. Current

![Peek 2019-03-28 15-55](https://user-images.githubusercontent.com/247363/55167838-fbd97e80-5171-11e9-9650-9a6c207dd829.gif)

2. Pinning at first panel show:

![Peek 2019-03-28 15-54](https://user-images.githubusercontent.com/247363/55167877-0eec4e80-5172-11e9-82d1-a2db48d0f993.gif)

What I'm missing in the API is (one of):
1. Which balloon position was selected from provided (so I could get return only this on consequent 'pin')
2. Recalculate position when pinned view changed view (right now I must call `panel.pin()` every time

At the moment I think that this is a feature for BallonPanelView.

/cc @oleq

**Comment by Reinmar** [comment]
I'd go with an easier solution for now. Which, IMO, may be to remove the mention. But if extending the style is easy to implement as well, then I'm fine with it too.

**Comment by oleq** [comment]
I agree, styling a part of the mention should remove that part from the mention. We can go with something more sophisticated in the future but for now, this will suffice.

**Comment by jodator** [comment]
> should remove that part from the mention

To be precise - it should remove whole mentino as we do not allow partial mentions in other cases (ie typing).

**Comment by oleq** [comment]
Partial removal makes more sense IMO but I guess it's harder to implement, right?

**Comment by jodator** [comment]
> Partial removal makes more sense IMO but I guess it's harder to implement, right?

We agreed that mention is full ie `@jodator` not `@jodat` so in that spirit we remove partial mentions.
