### ISSUE TITLE
Refresh feed items and update editor content

### ISSUE THREAD

**Issue by baptooo** [ckeditor/ckeditor5-mention#89]
Hello and thank you for this very nice plugin ! 👌 

I am reporting this issue as I didn't found any matching existing one.

## Describe the issue
When updating the feed values, the editor content is not updated with the new values.
I am looking for a way to update all the existing mentions in the model with the new values.

I tried to create a custom editor command called `mention:refresh` that will find every element that has the attribute `mention` and replace the `text` value with the incoming one but I didn't manage to do this...

Is it possible in the actual version of the plugin please ? Is there a simpler way to achieve this ?

Thank you very much !

## Screenshot
![2019-10-01 16 29 20](https://user-images.githubusercontent.com/1875595/65971629-bbccbe80-e468-11e9-94ca-19dc849f34b3.gif)

**Comment by jodator** [comment]
You can use `model.deleteContent()` and `editor.execute( 'mention' )` for that:

```js
editor.model.change( writer => {
	const mentions = Array.from( writer.createRangeIn( editor.model.document.getRoot() ) )
		// Filter out text nodes with mention.
		.filter( ( { type, item } ) => type === 'text' && item.hasAttribute( 'mention' ) )
		.map( value => value.item );

	for ( const nextMention of mentions ) {
		const range = writer.createRangeOn( nextMention );
		const insertNewMentionAt = range.start;

		// Remove previous mention.
		editor.model.deleteContent( writer.createSelection( range ) );

		// Insert new mention.
		const mentionText = '_____';
		editor.execute( 'mention', {
			marker: '@',
			// Set new mention data.
			mention: {
				id: '@Barney'
			},
			text: mentionText,
			range: editor.model.createRange( insertNewMentionAt )
		} );

		// Bonus: remove space after inserted mention.
		editor.model.deleteContent(
			writer.createSelection( writer.createRange(
				insertNewMentionAt.getShiftedBy( mentionText.length ),
				insertNewMentionAt.getShiftedBy( mentionText.length + 1 )
			) )
		);
	}
} );
```

ps.: this code replaces every mention in the document but you should get from the above snippet what you need.

**Comment by baptooo** [comment]
Hello @jodator thank you very much for your help it was exactly what I was looking for !
