### ISSUE TITLE
Should the `mention` class be in the data?

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-mention#9]
ATM the mention implementation detects:

```html
<span class="mention" data-mention="Foo">@foo</span>
```

The css class is outputed to the data and both `class` and `data-mention` are used to detect mention in the data.

**Comment by Reinmar** [comment]
Fine for me if it's there. Makes styling them easier if someone needs that. Does not cause issues that I see too.

**Comment by jodator** [comment]
So I clean the `mentioneditng.css` vs `mention.css` file names in this follow up.

> If we output mention class in data, then it goes to `cke5-mention/theme/mention.css` as content styles (edited)
